---
title: "CS5200 DBMS - Practicum 2 - Team Infinity"
output: html_notebook
Team : Kong Koon Kit, Zhiwei Bao, Luo Cheng Zhu
---

```{r}
library(XML)
library(RSQLite)

fpath <- "./"
dbfile <- "Practicum2.sqlite"
xmlfile <- "pubmed_sample.xml"

# if database file already exists, we connect to it, otherwise
# we create a new database
dbcon <- dbConnect(RSQLite::SQLite(), paste0(fpath,dbfile))
#dbExecute(dbcon, "PRAGMA foreign_keys = ON")
dbListTables(dbcon)
```

# Clean up 
```{sql connection = "dbcon"}
drop table if exists Article;
```

```{sql connection = "dbcon"}
drop table if exists ArticleAuthorMapping;
```

```{sql connection = "dbcon"}
drop table if exists Author;
```

```{sql connection = "dbcon"}
drop table if exists History;
```

```{sql connection = "dbcon"}
drop table if exists Journal;
```

```{sql connection = "dbcon"}
drop table if exists JournalIssue;
```


# Define Table Layout
```{sql connection ="dbcon"}
CREATE TABLE `Journal` (
  `ISSN`            Text NOT NULL PRIMARY KEY,
  `ISSNType`        Text NOT NULL,
  `Title`           Text NOT NULL,
  `ISOAbbreviation` Text NOT NULL
);


```

```{sql connection = "dbcon"}
CREATE TABLE `JournalIssue` (
  `JournalIssueID` Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `ISSN`           Text NOT NULL,
  `CitedMedium`    Text NOT NULL,
  `Volume`         Text NOT NULL,
  `Issue`          Text NOT NULL,
  `PubDate`        Date NOT NULL,
  CONSTRAINT JournalIssue_FK0 FOREIGN KEY (ISSN)         REFERENCES Journal (ISSN)      ON DELETE CASCADE
);
```

```{sql connection ="dbcon"}
CREATE TABLE `Article` (
  `PMID`         Text NOT NULL PRIMARY KEY,
  `ISSN`         Text NOT NULL,
  `ArticleTitle` Text NOT NULL,
  `Pagination`   Text NOT NULL,
  `AbstractID`   Integer NOT NULL,
  `Language`     Integer NOT NULL,
  `ArticleDate`  Date NOT NULL,
  CONSTRAINT Article_FK0 FOREIGN KEY (AbstractID)         REFERENCES Abstract (AbstractID)      ON DELETE CASCADE,
  CONSTRAINT Article_FK1 FOREIGN KEY (ISSN)               REFERENCES Journal (ISSN)             ON DELETE CASCADE
);
```

```{sql connection = "dbcon"}
CREATE TABLE `History` (
  `HistoryID` Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  `PMID`      Text NOT NULL,
  `PubStatus` Text NOT NULL,
  `PubDate`   Date NOT NULL,
  CONSTRAINT History_FK0 FOREIGN KEY (PMID)               REFERENCES Article (PMID)      ON DELETE CASCADE
);
```

```{sql connection = "dbcon"}
CREATE TABLE `Author` (
  `AuthorId`         Text NOT NULL PRIMARY KEY,
  `LastName`         Text NOT NULL,
  `ForeName`         Text NOT NULL,
  `Initials`         Text NOT NULL,
  `Affiliation`      Text NOT NULL
);

```

```{sql connection = "dbcon"}
CREATE TABLE `ArticleAuthorMapping` (
  `PMID`     Text NOT NULL,
  `AuthorId` Text NOT NULL,
  CONSTRAINT PublicationTypeList_FK0   FOREIGN KEY (PMID)          REFERENCES Article (PMID)      ON DELETE CASCADE,
  CONSTRAINT PArticleAuthorMapping_FK1 FOREIGN KEY (AuthorId)      REFERENCES Author (AuthorId)   ON DELETE CASCADE
);
```


# Process XML File

```{r }
fpn = paste0(fpath, xmlfile)
xmlDOM <- xmlParse(file = fpn)
xmlRoot <- xmlRoot(xmlDOM)
#head(xmlRoot)
```

# Define Data Frame

```{r}
History.df <- data.frame (HistoryID = integer(),
                          PMID = integer(),
                          PubStatus = character(),
                          PubDate = character(),
                          stringsAsFactors = F)

Author.df <- data.frame(AuthorID = character(),
                        LastName = character(), 
                        ForeName = character(),
                        Initialis = character(),
                        Affiliation = character(),
                        stringsAsFactors = F)

ArticleAuthorMapping.df <- data.frame(PMID = integer(), 
                                      AuthorID = character(),
                                      stringsAsFactors =)

Journal.df <- data.frame (ISSN = character(),
                          IssueType = character(),
                          Title = character(),
                          ISOAbbreviation = character(),
                          stringsAsFactors = F)

JournalIssue.df <- data.frame ( JournalIssueID = character(),
                                ISSN = character(),
                                CitedMedium = character(),
                                Volume = integer(),
                                Issue = integer(),
                                PubDate = character(),
                                stringsAsFactors = F)

Article.df <- data.frame (PMID = integer(),
                          ISSN = character(),
                          ArticleTitle = character(),
                          Pagination = character(),
                          Language = character(),
                          ArticleDate = character(),
                          stringsAsFactors = F)
```

# Defind Parser

```{r}
parseHistory <- function(pmid, history) 
{
  rows.df <-data.frame(HistoryID = integer(),
                       PMID = character(), 
                       PubStatus = character(),
                       PubDate = character(),
                       stringsAsFactors = F)

  # Use History DF record count as Auto Increment
  historyIdx <- nrow(History.df) + 10000000
  
  for (i in 1: xmlSize(history))
  {
    dataNode <- history[[i]]
    yy <- xpathSApply(dataNode, "Year", xmlValue)
    mm <- xpathSApply(dataNode, "Month", xmlValue)
    dd <- xpathSApply(dataNode, "Day", xmlValue)
    
    # Derived Field
    pubDate <- paste(yy, mm, dd, sep="-")
    
    # Create the "ID"
    historyIdx <- historyIdx + 1

    rows.df[i,1] <- historyIdx
    rows.df[i,2] <- pmid
    rows.df[i,3] <- xmlAttrs(dataNode, 2)
    rows.df[i,4] <- pubDate 
    
  }

  return(rows.df)
}
```

```{r}
parseAuthor <- function(authors) 
{
  rows.df <-data.frame(AuthorID = character(),
                       LastName = character(), 
                       ForeName = character(),
                       Initialis = character(),
                       Affiliation = character(),
                       stringsAsFactors = F)
  
  # Use actual row index since we skip some record if duplicated
  rowIdx = 1
  
  for (i in 1: xmlSize(authors))
  {
    dataNode <- authors[[i]]
    lastName <- xpathSApply(dataNode, "LastName", xmlValue)
    foreName <- xpathSApply(dataNode, "ForeName", xmlValue)
    initials <- xpathSApply(dataNode, "Initials", xmlValue)
    affiliation <- xpathSApply(dataNode, "Affiliation", xmlValue)
    
    authorID <- paste(lastName, initials, foreName, sep="-")
    
    if (length(affiliation) == 0 ) affiliation <- ''
    
    # If Author ID already exist in the record, skip insert
    if(!any(Author.df$AuthorID == authorID)) {
      rows.df[rowIdx,1] <- authorID
      rows.df[rowIdx,2] <- lastName
      rows.df[rowIdx,3] <- foreName
      rows.df[rowIdx,4] <- initials
      rows.df[rowIdx,5] <- affiliation
      rowIdx <- rowIdx + 1 
    }
  }

  return(rows.df)
}
```

```{r}
parseArticleAuthorMapping <- function(pmid, authors) 
{
  rows.df <-data.frame( PMID = integer(),
                        AuthorID = character(),
                        stringsAsFactors = F)

  for (i in 1: xmlSize(authors))
  {
    dataNode <- authors[[i]]
    lastName <- xpathSApply(dataNode, "LastName", xmlValue)
    foreName <- xpathSApply(dataNode, "ForeName", xmlValue)
    initials <- xpathSApply(dataNode, "Initials", xmlValue)

    authorID <- paste(lastName, initials, foreName, sep="-")
    
    rows.df[i,1] <- authorID
    rows.df[i,2] <- pmid
  }

  return(rows.df)
}
```

```{r}
parseJournal <- function(journals) 
{
  rows.df <- data.frame (ISSN = character(),
                         IssueType = character(),
                         Title = character(),
                         ISOAbbreviation = character(),
                         stringsAsFactors = F)

  for (i in 1: xmlSize(journals))
  {
    dataNode <- journals[[i]]
    issn <- xpathSApply(dataNode, "ISSN", xmlValue)
    issueType <- xpathSApply(dataNode, "ISSN", xmlAttrs)
    title <- xpathSApply(dataNode, "Title", xmlValue)
    isoAbbreviation <- xpathSApply(dataNode, "ISOAbbreviation", xmlValue)

    rows.df[i,1] <- issn
    rows.df[i,2] <- issueType
    rows.df[i,3] <- title
    rows.df[i,4] <- isoAbbreviation
  }

  return(rows.df)
}
```

```{r}
parseJournalIssue <- function(journals) 
{
  rows.df <- data.frame (JournalIssueID = character(),
                         ISSN = character(),
                         CiteMedium = character(),
                         Volume = integer(),
                         Issue = integer(),
                         PubDate = character(),
                         stringsAsFactors = F)

  # Use Journal Issue DF record count as Auto Increment
  journalIdx <- nrow(JournalIssue.df) + 10000000

  for (i in 1: xmlSize(journals))
  {
    dataNode <- journals[[i]]
    issn <- xpathSApply(dataNode, "ISSN", xmlValue)
    citedMedium <- xpathSApply(dataNode, "JournalIssue", xmlAttrs)
    volume <- xpathSApply(dataNode, "JournalIssue/Volume", xmlValue)
    issue <- xpathSApply(dataNode, "JournalIssue/Issue", xmlValue)
    pubDate <- xpathSApply(dataNode, "JournalIssue/PubDate", xmlValue)

    journalIdx <- journalIdx + 1
    rows.df[i,1] <- journalIdx
    rows.df[i,2] <- issn
    rows.df[i,3] <- citedMedium
    rows.df[i,4] <- volume
    rows.df[i,5] <- issue
    rows.df[i,6] <- pubDate
  }

  return(rows.df)
}
```

```{r}
parseArticle <- function(pmid, article) 
{
  rows.df <- data.frame (PMID = integer(),
                         ISSN = character(),
                         ArticleTitle = character(),
                         Pagination = character(),
                         Language = character(),
                         ArticleDate = character(),
                         stringsAsFactors = F)
  
  for (i in 1: xmlSize(article))
    {
      dataNode <- article[[i]]
      articleTitle = xpathSApply(dataNode, "ArticleTitle", xmlValue)
      pagination = xpathSApply(dataNode, "Pagination/MedlinePgn", xmlValue)
      language = xpathSApply(dataNode, "Language", xmlValue)
      issn = xpathSApply(dataNode, "Journal/ISSN", xmlValue)
      yy = xpathSApply(dataNode, "ArticleDate/Year", xmlValue)
      mm = xpathSApply(dataNode, "ArticleDate/Month", xmlValue)
      dd = xpathSApply(dataNode, "ArticleDate/Day", xmlValue)
  
      # Derived Field    
      articleDate <- paste(yy, mm, dd, sep="-")
      if (length(articleDate) == 0) articleDate <- '1970-01-01'
      
      rows.df[i,1] <- pmid
      rows.df[i,2] <- issn
      rows.df[i,3] <- articleTitle
      rows.df[i,4] <- pagination
      rows.df[i,5] <- language
      rows.df[i,6] <- articleDate
    }
  
    return(rows.df)
}
```

# Main Parsing
```{r}
size <- xmlSize(xmlRoot)
for (i in 1 : size){
  node = xmlRoot[[i]]
  pmid = xmlValue(xpathSApply(node[[1]], "PMID"))

  # Process Journal
  journals = xpathApply(node[[1]], "Article/Journal")
  journalRows <- parseJournal(journals)
  for(j in 1 : nrow(journalRows)) {
    row <- journalRows[j,]
    Journal.df[nrow(Journal.df) + 1,] = row
  }
  
  # Process Journal Issue
  journalIssueRows <- parseJournalIssue(journals)
  for(j in 1 : nrow(journalIssueRows)) {
    row <- journalIssueRows[j,]
    JournalIssue.df[nrow(JournalIssue.df) + 1,] = row
  }
  
  # Process History
  history = xpathApply(node[[2]], "History/PubMedPubDate")
  historyRows <- parseHistory(pmid, history)
  for(j in 1 : nrow(historyRows)) {
    row <- historyRows[j,]
    History.df[nrow(History.df) + 1,] = row
  }
  
  # Process Author (Record will be skipped if it was added previously)
  authors = xpathApply(node[[1]], "Article/AuthorList/Author")
  authorRows <- parseAuthor(authors)
  if (nrow(authorRows) > 0){
    for(j in 1 : nrow(authorRows)) {
      row <- authorRows[j,]
      Author.df[nrow(Author.df) + 1,] = row
    }
  }
  
  # Process Article Author Mapping
  articleAuthorMappingRows <- parseArticleAuthorMapping(pmid, authors)
  for(j in 1 : nrow(articleAuthorMappingRows)) {
    row <- articleAuthorMappingRows[j,]
    ArticleAuthorMapping.df[nrow(ArticleAuthorMapping.df) + 1,] = row
  }
  
  # Process Article
  article = xpathApply(node[[1]], "Article")
  articleRows <- parseArticle(pmid, article)
  for(j in 1 : nrow(articleRows)) {
    row <- articleRows[j,]
    Article.df[nrow(Article.df) + 1,] = row
  }
}

```

```{r}
History.df
Author.df
ArticleAuthorMapping.df
Article.df
Journal.df
JournalIssue.df
```

# Write Result into database

```{r}
dbWriteTable(dbcon, "Article", Article.df, overwrite = T)
dbWriteTable(dbcon, "ArticleAuthorMapping", ArticleAuthorMapping.df, overwrite = T)
dbWriteTable(dbcon, "Author", Author.df, overwrite = T)
dbWriteTable(dbcon, "History", History.df, overwrite = T)
dbWriteTable(dbcon, "Journal", Journal.df, overwrite = T)
dbWriteTable(dbcon, "JournalIssue", JournalIssue.df, overwrite = T)
```

# Finally View the record via SQL
```{sql connection = "dbcon"}
select rowid, a.* from Article a
```

```{sql connection = "dbcon"}
select rowid, a.* from ArticleAuthorMapping a
```

```{sql connection = "dbcon"}
select rowid, a.* from Author a
```

```{sql connection = "dbcon"}
select rowid, a.* from History a
```

```{sql connection = "dbcon"}
select rowid, a.* from Journal a
```

```{sql connection = "dbcon"}
select rowid, a.* from JournalIssue a
```